# goreleaser.yml
# Build customization
project_name: tsuru
version: 2
builds:
- main: ./tsuru
  binary: tsuru
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - 386
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
    - goos: windows
      goarch: arm64
  env:
    - CGO_ENABLED=0
    - META_PROJECT_NAME={{.ProjectName}}
    - META_VERSION={{.Version}}
    - META_TAG={{.Tag}}
    - META_PREVIOUS_TAG={{.PreviousTag}}
    - META_COMMIT={{.Commit}}
    - META_DATE={{.Date}}
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}
  hooks:
    post:
      - ./misc/generate_metadata.sh dist/metadata.json


# Archive customization
archives:
- name_template: >-
    {{ .ProjectName }}_
    {{- .Version }}_
    {{- if eq .Os "darwin" -}}
      macOS
    {{- else -}}
      {{ .Os }}
    {{- end }}_
    {{- .Arch }}
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - misc/bash-completion
    - misc/zsh-completion

release:
  extra_files:
    - glob: dist/metadata.json
    - glob: dist/CHANGELOG.md

  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  prerelease: auto

# Mac OS Homebrew
brews:
  # Reporitory to push the tap to.
- repository:
    owner: tsuru
    name: homebrew-tsuru
    token: "{{ .Env.HOMEBREW_TSURU_REPOSITORY_AUTH_TOKEN }}"

  description: "tsuru-client is a tsuru command line tool for application developers."
  homepage: "https://docs.tsuru.io/stable/"

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  directory: Formula

  # Custom install
  install: |
    bin.install "tsuru"
    bash_completion.install "misc/bash-completion" => "tsuru"
    zsh_completion.install "misc/zsh-completion" => "tsuru"

  # If set to auto, the release will not be uploaded to the homebrew tap
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  skip_upload: auto

aurs:
- name: tsuru-bin
  description: "tsuru-client is a tsuru command line tool for application developers."
  homepage: "https://tsuru.io"
  license: "BSD-3-Clause"

  maintainers:
  - "Tsuru <tsuru@g.globo>"
  - "Claudio Netto <nettinhorama@gmail.com>"

  skip_upload: auto

  git_url: "ssh://aur@aur.archlinux.org/tsuru-bin.git"
  private_key: "{{ .Env.AUR_KEY }}"
