#!/usr/bin/env sh
# Copyright © 2023 tsuru-client authors
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

set -eu
LANG=utf8

git_authors="$(git log HEAD origin/beta-v2 | git shortlog -se)"
git_authors="$(echo "${git_authors}" | sed -E "s/[[:space:]]+/ /g" | cut -d' ' -f3- | sort -f )"
contributors=$(echo "${git_authors}" \
  | awk 'BEGIN { FS="<"}
    {arr[$1] = arr[$1] "<" $2 " "}
    END {for (i in arr) print i arr[i]}' \
  | sed 's/[[:space:]]$//' \
  | sort -f )

echo "# AUTOGENERATED FILE - DO NOT EDIT
#
# This is the official list of people who have contributed code to tsuru-client.
# The AUTHORS file lists the copyright holders; this file lists people.
# For example, Globo.com employees are listed here but not in AUTHORS,
# because Globo.com holds the copyright.
#
# This file was generated by scripts/contributors_file.sh

${contributors}"
