#!/usr/bin/env sh
# Copyright © 2023 tsuru-client authors
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This script generates a coverage badge for this Go project.
set -eu

coverage_file="coverage/coverage.txt" # generated by `go tool cover -func=coverage/coverage.out -o coverage/coverage.txt`
coverage_label="coverage"
badge_file="coverage/badge.svg"

coverage="$(tail -n1 "${coverage_file}" \
  | sed 's/[[:space:]]/ /g' \
  | rev | cut -d' ' -f1 | rev \
  )"
number="$(echo "${coverage}" | sed "s/%//")"
decimal="$(echo "${number}" | cut -d'.' -f1)"

color="lightgrey"
case "${decimal}" in
    100) color="brightgreen" ;;
    9[0-9]) color="brightgreen" ;;
    8[0-9]) color="green" ;;
    [5-8][0-9]) color="yellow" ;;
    [1-4][0-9]) color="red" ;;
    [0-9]) color="red" ;;
esac

badge_url="https://img.shields.io/badge/${coverage_label}-${number}%25-${color}.svg"
curl -sL -o "${badge_file}" "${badge_url}"
