package main

import (
	"flag"
	"io"
	"io/ioutil"
	"os"
	"strings"
)

func main() {
	outName := flag.String("o", "", "output file")
	flag.Parse()
	fs, err := ioutil.ReadDir(".")
	if err != nil {
		panic(err)
	}
	out, err := os.Create(*outName)
	if err != nil {
		panic(err)
	}
	out.Write([]byte("// Code generated by generator/main.go, DO NOT EDIT.\n\n"))
	out.Write([]byte("package config \n\nconst (\n"))
	for _, f := range fs {
		if strings.HasSuffix(f.Name(), ".yml") {
			out.Write([]byte(strings.Title(strings.TrimSuffix(f.Name(), ".yml")) + " = `"))
			f, _ := os.Open(f.Name())
			io.Copy(out, f)
			out.Write([]byte("`\n"))
		}
	}
	out.Write([]byte(")\n"))
}
